### ISSUE TITLE
Problem inferring file type from file path in newer Android versions

### ISSUE THREAD

**Issue by nfdz** [NordicSemiconductor/Android-DFU-Library#101]
Hi all,

I've had problems updating only bootloader zip files whereas I've had no problem with application .zip files. My error was related with Manifest file validation _"Manifest file must specify at least one file."_. 

I dived deep into the library code and I have found these lines:

```java
int fileType = intent.getIntExtra(EXTRA_FILE_TYPE, TYPE_AUTO);
if (filePath != null && fileType == TYPE_AUTO)
	fileType = filePath.toLowerCase(Locale.US).endsWith("zip") ? TYPE_AUTO : TYPE_APPLICATION;
```
https://github.com/NordicSemiconductor/Android-DFU-Library/blob/release/dfu/src/main/java/no/nordicsemi/android/dfu/DfuBaseService.java#L917

This logic is wrong because in the latest versions of Android require storage permission if you want full file system access. If you don't manage file picking by yourself (with storage permission) you get an URI and path like this: 
_"/document/1906"_

I don't understand why this line of code is at the initialization of the DFU service but I don't think that is right.

The current workaround would be not to use file type auto and manage the scope manually.

Regards,
Noé

**EDIT**:  Another easier and quicker workaround to implement is the following (before passing the variable to _DfuServiceInitiator_):
```java
filePath += "zip";
```
or
```java
filePath = null;
```
If you provide a valid fileUri, the current implementation won't care about if the filePath is valid. (I do not like this workaround for production because it is coupled to current library version implementation)

**Comment by philips77** [comment]
Hi, 
But if EXTRA_FILE_TYPE is set to auto, and your filePath is null (you're saying you're using fileUri) then if will not go into this if.
This code is for legacy reasons as some apps may not set fileType (there were times without the dfuServiceInitiator).

**Comment by nfdz** [comment]
Ok, you are totally right. However, I don't feel intuitive at all and someone could loose time looking for strange errors. Maybe it is time to deprected more methods in the initializator, write a big warning/disclaimer or annotate with @Nullable at least.
```java
/**
 * Sets the URI or path of the ZIP file. If the URI and path are not null the URI will be used.
 * @param uri the URI of the file
 * @param path the path of the file
 * @return the builder
 */
public DfuServiceInitiator setZip(final Uri uri, final String path) {
	return init(uri, path, 0, DfuBaseService.TYPE_AUTO, DfuBaseService.MIME_TYPE_ZIP);
}
```
https://github.com/NordicSemiconductor/Android-DFU-Library/blob/release/dfu/src/main/java/no/nordicsemi/android/dfu/DfuServiceInitiator.java#L392
Now I know that I should use only the one with URI parameter.
Thanks
