### ISSUE TITLE
DfuBaseService: Connection state change error: 8 newState: 0

### ISSUE THREAD

**Issue by jingmo0319** [NordicSemiconductor/Android-DFU-Library#103]
When I upgraded the firmware to 100 percent, I thought the upgrade was successful, but it threw an exception. Who knows what caused it?My diary is as follows, please help me!
```
04-23 15:48:00.117 4995-5065/com.risoo.app E/DfuBaseService: Connection state change error: 8 newState: 0
04-23 15:48:00.118 4995-5158/com.risoo.app E/DfuImpl: Disconnected while sending data
04-23 15:48:00.118 4995-5158/com.risoo.app E/DfuBaseService: Uploading Firmware Image failed: device disconnected
04-23 15:48:00.125 4995-4995/com.risoo.app E/bm: onDeviceDisconnected
04-23 15:48:00.127 4995-4995/com.risoo.app E/bm: onError=4096     errorType=0   message=DFU DEVICE DISCONNECTED
```

**Comment by philips77** [comment]
Could you paste a bit more log? What happens before that.

**Comment by jingmo0319** [comment]
04-23 16:59:30.666 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onDfuProcessStarting-deviceAddress=CE:99:42:70:BA:CF
04-23 16:59:32.936 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onEnablingDfuMode-deviceAddress=CE:99:42:70:BA:CF
04-23 16:59:35.274 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onDeviceConnecting()-deviceAddress=CE:99:42:70:BA:CF
04-23 16:59:36.475 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onDfuProcessStarting-deviceAddress=CE:99:42:70:BA:CF
04-23 16:59:41.949 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=0
04-23 16:59:42.016 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=1
04-23 16:59:42.045 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=2
04-23 16:59:42.073 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=3
04-23 16:59:42.095 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=4
04-23 16:59:42.124 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=5
04-23 16:59:42.149 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=6
04-23 16:59:42.180 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=7
04-23 16:59:42.205 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=8
04-23 16:59:42.249 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=9
04-23 16:59:42.278 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=10
04-23 16:59:42.308 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=11
04-23 16:59:42.349 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=12
04-23 16:59:42.372 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=13
04-23 16:59:42.397 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=14
04-23 16:59:42.419 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=15
04-23 16:59:42.445 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=16
04-23 16:59:42.471 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=17
04-23 16:59:42.500 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=18
04-23 16:59:42.522 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=19
04-23 16:59:45.650 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=20
04-23 16:59:45.742 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=21
04-23 16:59:45.770 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=22
04-23 16:59:45.790 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=23
04-23 16:59:45.815 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=24
04-23 16:59:45.861 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=25
04-23 16:59:45.892 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=26
04-23 16:59:45.912 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=27
04-23 16:59:45.940 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=28
04-23 16:59:45.966 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=29
04-23 16:59:49.121 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=30
04-23 16:59:49.217 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=31
04-23 16:59:49.246 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=32
04-23 16:59:49.269 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=33
04-23 16:59:49.297 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=34
04-23 16:59:49.319 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=35
04-23 16:59:49.343 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=36
04-23 16:59:49.363 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=37
04-23 16:59:49.387 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=38
04-23 16:59:49.409 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=39
04-23 16:59:52.531 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=40
04-23 16:59:52.602 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=41
04-23 16:59:52.628 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=42
04-23 16:59:52.647 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=43
04-23 16:59:52.666 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=44
04-23 16:59:52.687 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=45
04-23 16:59:52.708 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=46
04-23 16:59:52.728 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=47
04-23 16:59:52.747 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=48
04-23 16:59:52.765 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=49
04-23 16:59:55.878 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=50
04-23 16:59:55.966 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=51
04-23 16:59:55.990 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=52
04-23 16:59:56.016 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=53
04-23 16:59:56.036 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=54
04-23 16:59:56.062 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=55
04-23 16:59:56.083 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=56
04-23 16:59:56.108 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=57
04-23 16:59:56.134 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=58
04-23 16:59:59.318 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=59
04-23 16:59:59.410 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=60
04-23 16:59:59.439 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=61
04-23 16:59:59.469 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=62
04-23 16:59:59.497 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=63
04-23 16:59:59.514 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=64
04-23 16:59:59.531 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=65
04-23 16:59:59.549 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=66
04-23 16:59:59.574 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=67
04-23 16:59:59.607 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=68
04-23 17:00:02.710 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=69
04-23 17:00:02.793 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=70
04-23 17:00:02.824 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=71
04-23 17:00:02.844 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=72
04-23 17:00:02.862 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=73
04-23 17:00:02.880 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=74
04-23 17:00:02.899 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=75
04-23 17:00:02.919 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=76
04-23 17:00:02.936 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=77
04-23 17:00:02.958 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=78
04-23 17:00:06.051 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=79
04-23 17:00:06.116 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=80
04-23 17:00:06.136 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=81
04-23 17:00:06.159 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=82
04-23 17:00:06.178 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=83
04-23 17:00:06.199 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=84
04-23 17:00:06.219 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=85
04-23 17:00:06.237 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=86
04-23 17:00:06.257 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=87
04-23 17:00:06.277 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=88
04-23 17:00:09.424 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=89
04-23 17:00:09.507 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=90
04-23 17:00:09.535 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=91
04-23 17:00:09.558 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=92
04-23 17:00:09.576 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=93
04-23 17:00:09.596 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=94
04-23 17:00:09.621 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=95
04-23 17:00:09.645 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=96
04-23 17:00:09.662 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=97
04-23 17:00:12.755 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=98
04-23 17:00:12.827 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=99
04-23 17:00:12.860 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=100
04-23 17:00:17.048 11901-12390/no.nordicsemi.android.nrftoolbox E/DfuBaseService: Unable to write Op Code: device disconnected
04-23 17:00:17.059 11901-11901/no.nordicsemi.android.nrftoolbox E/bm: onError-deviceAddress=CE:99:42:70:BA:CF error=4096 errorType=0 message=DFU DEVICE DISCONNECTED

**Comment by philips77** [comment]
Could you enable debug log in the lib? Return true from isDebug in your DfuService class. And then paste the log, but just from around 98%, the ending.

**Comment by jingmo0319** [comment]
I hava enabled debug log in the lib:
public class DfuService extends DfuBaseService {

    @Override
    protected Class<? extends Activity> getNotificationTarget() {
        /*
		 * As a target activity the NotificationActivity is returned, not the MainActivity. This is because the notification must create a new task:
		 * 
		 * intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
		 * 
		 * when user press it. Using NotificationActivity we can check whether the new activity is a root activity (that means no other activity was open before)
		 * or that there is other activity already open. In the later case the notificationActivity will just be closed. System will restore the previous activity.
		 * However if the application has been closed during upload and user click the notification a NotificationActivity will be launched as a root activity.
		 * It will create and start the main activity and terminate itself.
		 * 
		 * This method may be used to restore the target activity in case the application was closed or is open. It may also be used to recreate an activity
		 * history (see NotificationActivity).
		 */
        return NotificationActivity.class;
    }

    @Override
    protected boolean isDebug() {
        return true;
    }
}

But I only get the following logs:
04-23 17:26:26.595 18898-18898/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=98
04-23 17:26:26.615 18898-18898/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=99
04-23 17:26:26.643 18898-18898/no.nordicsemi.android.nrftoolbox E/bm: onProgressChanged-deviceAddress=CE:99:42:70:BA:CF percent=100
04-23 17:26:31.187 18898-19295/no.nordicsemi.android.nrftoolbox E/DfuBaseService: Unable to write Op Code: device disconnected
04-23 17:26:31.215 18898-18898/no.nordicsemi.android.nrftoolbox E/bm: onError-deviceAddress=CE:99:42:70:BA:CF error=4096 errorType=0 message=DFU DEVICE DISCONNECTED
How do I get more logs?

**Comment by philips77** [comment]
Are you using Legacy or Secure DFU?
Looks like you have filtered only to Error logs in your LogCat.

**Comment by philips77** [comment]
Did you manage to solve the issue?
