### ISSUE TITLE
Integration of DFU Library

### ISSUE THREAD

**Issue by Ktm250fx** [NordicSemiconductor/Android-DFU-Library#107]
Hello 

I am following your instructions to integrate a DFU Library into my APP on Android
I am using Android Studio for that purpose 3.1.2
I followed the following instructions:

_However, if you want to modify the code to your needs you have to clone the project and add it as follows:

Clone the project into DFULibrary folder (by default it will be cloned into Android-DFU-Library folder) to your projects root, for example to AndroidstudioProjects.
Add the dfu module to your project:
Add '..:DFULibrary:dfu' to the settings.gradle file:
include ':dfu'
project(':dfu').projectDir = file('../DFULibrary/dfu')
Open Project Structure -> Modules -> app -> Dependencies tab and add dfu module dependency. You may also edit the build.gradle file in your app module manually by adding the following dependency: compile project(':dfu')_

However upon attempt to build I get the following errors:

Unable to resolve dependency for ':Application@debug/compileClasspath': Could not resolve project :dfu.
Open File
Show Details

<img width="1826" alt="screen shot 2018-05-28 at 9 27 43" src="https://user-images.githubusercontent.com/39689416/40600259-75707f36-6259-11e8-9260-1c7169d7e6de.png">
More details in picture

null |  
-- | --
/Users/ishvorin/Documents/WirelessFreedom/triplejump/android/techapp |  
Application/build.gradle |  
Unable to resolve dependency for ':Application@debug/compileClasspath': Could not resolve project :dfu. |  
Unable to resolve dependency for ':Application@debugAndroidTest/compileClasspath': Could not resolve project :dfu. |  
Unable to resolve dependency for ':Application@debugUnitTest/compileClasspath': Could not resolve project :dfu. |  
Unable to resolve dependency for ':Application@release/compileClasspath': Could not resolve project :dfu. |  
Unable to resolve dependency for ':Application@releaseUnitTest/compileClasspath': Could not resolve project :dfu. |  

By any chance do you have any idea what I am doing wrong?

**Comment by philips77** [comment]
Hi, sorry for the delay, did you manage to fix your problem?
