### ISSUE TITLE
The device is being upgraded, and at this point I want to stop, what method should I call?

### ISSUE THREAD

**Issue by zhouzhijin0908** [NordicSemiconductor/Android-DFU-Library#115]
The device is being upgraded, and at this point I want to stop, what method should I call?

**Comment by philips77** [comment]
The DfuServiceInitiator [start(...)]([https://github.com/NordicSemiconductor/Android-DFU-Library/blob/release/dfu/src/main/java/no/nordicsemi/android/dfu/DfuServiceInitiator.java#L603])) method returns the [controller](https://github.com/NordicSemiconductor/Android-DFU-Library/blob/release/dfu/src/main/java/no/nordicsemi/android/dfu/DfuController.java).
