### ISSUE TITLE
If the device is being upgraded, I want to stop completely.

### ISSUE THREAD

**Issue by zhouzhijin0908** [NordicSemiconductor/Android-DFU-Library#117]
If the device is being upgraded, I want to stop completely.How to handle it?

There was an error in the upgrade process. I want to stop the upgrade service completely.How to handle it?

final Intent intent = new Intent(ProtocolUtils.getInstance().getContext(), DFUService.class);
ProtocolUtils.getInstance().getContext().stopService(intent);
Can this stop?

**Comment by zhouzhijin0908** [comment]
final Intent intent = new Intent(ProtocolUtils.getInstance().getContext(), DFUService.class);
        ProtocolUtils.getInstance().getContext().stopService(intent);
---------------------------------------------------------
Can this stop?

**Comment by philips77** [comment]
No. You have to call cancel() method from the controller. It will stop the service.

**Comment by zhouzhijin0908** [comment]
**Which controller?Which API is specifically invoked?**

**Comment by philips77** [comment]
When you initiate the dfu process with dfuServiceInitiator, the start(..) method returns a controller. If you'd check it's source code, it just sends some broadcast messages, so you may also do this on your own instead.
