### ISSUE TITLE
Program type already present: no.nordicsemi.android.dfu.BaseButtonlessDfuImpl$ButtonlessBluetoothCallback

### ISSUE THREAD

**Issue by Basavaraj1991** [NordicSemiconductor/Android-DFU-Library#119]
Hi

I'm getting the below issue while generating the signed apk with debug and release.

Program type already present: no.nordicsemi.android.dfu.BaseButtonlessDfuImpl$ButtonlessBluetoothCallback

**Comment by philips77** [comment]
Duplicate of #118
