### ISSUE TITLE
Proguard configuration missing

### ISSUE THREAD

**Issue by natangr** [NordicSemiconductor/Android-DFU-Library#13]
I'm using proguard and minifyEnabled in my project in the release build and I'm not able to get the device in DFU mode. The debug build has minifyEnabled set to false and works as expected.

My question is, what should I add to the proguard-rules for this library?

**Comment by natangr** [comment]
I found the solution, I'm leaving the answer here in case someone else have this issue. All I had to do is add the following to my proguard-rules.pro:
`-keep class no.nordicsemi.android.dfu.** { *; }`

**Comment by philips77** [comment]
Thanks! I'll write it to the README file and close the issue.

**Comment by philips77** [comment]
I've added information about proguard to Android-DFU-Library project's readme file: https://github.com/NordicSemiconductor/Android-DFU-Library/commit/269cb53a3aed6c876f76ec0786c8a31d555bf1f5
Thanks again, closing.
