### ISSUE TITLE
BaseDfuImpl.java  initialize error

### ISSUE THREAD

**Issue by gjjofsfe** [NordicSemiconductor/Android-DFU-Library#148]
In `BaseDfuImpl` when initialize method execute, `firmwareStream.reset()` throws an exception.
The reason is that `InputStream` does not support mark.
So, I suggest that change it to:
```java
try {
	if (firmwareStream.markSupported()) {
		firmwareStream.reset();
	}
	size = firmwareStream.available();
} catch (final Exception e) {
	size = 0;
	// not possible
}
```

**Comment by philips77** [comment]
Are you using a ZIP file, or BIN or HEX files with the firmware?

**Comment by gjjofsfe** [comment]
> Are you using a ZIP file, or BIN or HEX files with the firmware?

yes, I use a BIN file to update.

**Comment by philips77** [comment]
It will be released in the next version.
