### ISSUE TITLE
Sync gradle error when work with androidx 2.0.0

### ISSUE THREAD

**Issue by dubiao** [NordicSemiconductor/Android-DFU-Library#154]
It goes wrong when working with androidx:2.0.0
> androidx.lifecycle:lifecycle-extensions:2.0.0

output:
```
Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86
	is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory)
```

I think this line cause the problem:
https://github.com/NordicSemiconductor/Android-DFU-Library/blob/5f31317d8b659b862b600c730d05229fae96f195/dfu/build.gradle#L61

While the [scanner](https://github.com/NordicSemiconductor/Android-Scanner-Compat-Library) and [ble](https://github.com/NordicSemiconductor/Android-BLE-Library) library work fine.

**Comment by philips77** [comment]
Add `implementation 'androidx.core:core:1.0.0'` in your app's dependencies to override.
