### ISSUE TITLE
Rely on dfu to report an error

### ISSUE THREAD

**Issue by mshandan** [NordicSemiconductor/Android-DFU-Library#157]
Error:(61, 0) Could not find method implementation() for arguments [com.android.support:support-core-utils:28.0.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

so what should I do？ Thanks.

**Comment by philips77** [comment]
Please check out this link: https://stackoverflow.com/questions/45615474/gradle-error-could-not-find-method-implementation-for-arguments-com-android
You need to set up your Android Studio properly. We are using Gradle wrapper 4.10.2 and Android Studio 3.2.1.

**Comment by mshandan** [comment]
Thank you so much for your assistance.I wonder how it can support in Android Studio 3.0.1 because of   It's difficult to change the version of my APP.Or is there any other way to solve this problem.




------------------ 原始邮件 ------------------
发件人: "Aleksander Nowakowski"<notifications@github.com>;
发送时间: 2018年12月19日(星期三) 下午4:52
收件人: "NordicSemiconductor/Android-DFU-Library"<Android-DFU-Library@noreply.github.com>;
抄送: "菡萏"<1654381733@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NordicSemiconductor/Android-DFU-Library] Rely on dfu to reportan error (#157)




Please check out this link: https://stackoverflow.com/questions/45615474/gradle-error-could-not-find-method-implementation-for-arguments-com-android
 You need to set up your Android Studio properly. We are using Gradle wrapper 4.10.2 and Android Studio 3.2.1.
