### ISSUE TITLE
Permission Error - SELinux

### ISSUE THREAD

**Issue by langerleeor** [NordicSemiconductor/Android-DFU-Library#159]
Hello Nordic Support,
I am using the latest Android DFU Android Toolbox with partial success. On most phones the firmware update runs perfect. On certain Android phones I'm getting the following error:

`SELinux: avc:  denied  { find } for service=opdiagnose pid=8327 uid=10212 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
`

I am using the same methodology as in the readme:

```
final DfuServiceInitiator starter = new DfuServiceInitiator(mudra.getBluetoothDevice().getAddress())
                .setDeviceName(mudra.getBluetoothDevice().getName())
                .setKeepBond(true);
        starter.setUnsafeExperimentalButtonlessServiceInSecureDfuEnabled(true);
```

More information on SELinux permisisons can be found [here](https://source.android.com/security/selinux/images/SELinux_Treble.pdf).
When running the same DFU flow via the nRF Connect app, the update runs smoothly. 
How do I overcome these permission issues?

**Comment by philips77** [comment]
Hi, sorry, I have no knowledge about SELinux. Could you please ask on DevZone? Our support team can handle from there. Thank you!
