### ISSUE TITLE
How do lower versions of apps rely on dfu

### ISSUE THREAD

**Issue by mshandan** [NordicSemiconductor/Android-DFU-Library#160]
Thank you so much for your assistance.I wonder how it can support in Android Studio 3.0.1 because of   It's difficult to change the version of my APP.Or is there any other way to solve this problem.

**Comment by philips77** [comment]
Hello!
DFU will work only with Android 4.3, as this version added support for Bluetooth LE. You may add the library to your app, but disable this feature for older Android versions.
You'd have to include the DFU library as a module (clone repo, and add as module as described in Readme), change minSdkVersion to what you need and don't use it before API 18 as it will crash. Perhaps you'll need to suppress some warnings.

**Comment by philips77** [comment]
https://github.com/NordicSemiconductor/Android-DFU-Library/tree/release/documentation#integration

**Comment by mshandan** [comment]
Yes, I do need to use Android Studio 3.0.1 , but what should I do? Can I be more specific? Thank you！

**Comment by mshandan** [comment]
Hello,when I change compileSdkVersion 28 to compileSdkVersion 25,the following error was generated:
 Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':dfu'.
      > Could not resolve all dependencies for configuration ':dfu:_releasePublishCopy'.
         > Could not resolve com.android.support:support-core-utils:25.4.0.
           Required by:
               project :dfu
            > Could not resolve com.android.support:support-core-utils:25.4.0.

**Comment by mshandan** [comment]
![1546926645 1](https://user-images.githubusercontent.com/45030023/50812201-cf6d4d80-134c-11e9-8ca9-dc89675a65c7.png)

**Comment by philips77** [comment]
Well.. in API 25 there was no API for Bluetooth 5 features, so you need to remove/comment out those parts. All related to PHY, perhaps something more.
I assume you've solved the problem with https://mvnrepository.com/artifact/com.android.support/support-core-utils/25.4.0?

**Comment by mshandan** [comment]
Okay, so I've removed those errors and the program works, and I've created DfuService and NotificationActivity as the documentation says.But now what can I do to achieve a buttonless dfu upgrade?

**Comment by philips77** [comment]
The buttonless upgrade should work out of the box if you didn't modify the bootloader or the buttonless service in your firmware. Just start the DFU process using `DfuServiceInitiator` as described in Readme.

**Comment by mshandan** [comment]
If I use a local zip package to implement the dfu upgrade, how do I set mFileStreamUri and mFilePath?

if (mFileType == DfuService.TYPE_AUTO)
    starter.setZip(mFileStreamUri, mFilePath);

**Comment by roshanrajaratnam** [comment]
Hi @mshandan, In order to do this you will have to get the uri of the file you wish to flash using a file manager that's available in the device. You need to open the file chooser app and then upon selecting the file you can get the uri and filepath in the `onActivityResult(final int requestCode, final int resultCode, final Intent data)` callback. Please take a look our toolbox example on how to [open](https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/master/app/src/main/java/no/nordicsemi/android/nrftoolbox/dfu/DfuActivity.java#L672) the file chooser and how to get the [uri](https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/master/app/src/main/java/no/nordicsemi/android/nrftoolbox/dfu/DfuActivity.java#L425).

Hope this helps

**Comment by mshandan** [comment]
This is what I wrote after connecting bluetooth. Below are the code and the contents in debug. I want to know why it doesn't work and what I should do.Thank you very much for your help.


            final DfuServiceInitiator starter = new DfuServiceInitiator(gatt.getDevice().getAddress())
                    .setDeviceName(gatt.getDevice().getName())
                    .setKeepBond(true);
          
            starter.setUnsafeExperimentalButtonlessServiceInSecureDfuEnabled(true);
            System.out.println(" 11****dfu: "+ starter);
            starter.setZip(R.raw.app2);
            System.out.println(" ****dfu: "+ starter);
            final DfuServiceController controller =starter.start(context,DfuService.class);


System.out:  11****dfu: no.nordicsemi.android.dfu.DfuServiceInitiator@7d1e772
System.out:  ****dfu: no.nordicsemi.android.dfu.DfuServiceInitiator@7d1e772

**Comment by mshandan** [comment]
Hi, do I need to create a new class to implement DfuServiceInitiator starter, or just connect to bluetooth and get the MAC address and name to implement it.

**Comment by philips77** [comment]
Your code looks ok. Did you add your DfuService to the *AndroidManifest.xml*?

Is your device based on SDK 12? If not, you may remove `starter.setUnsafeExperimentalButtonlessServiceInSecureDfuEnabled(true);`
Is your device bonded and remains bonded while DFU process? This was introduces in SDK 14, afair, or SDK 8-11. If not, you may remove `.setKeepBond(true)`.

**Comment by mshandan** [comment]
I've been adding Dfuservice to androidmanifest.xml since the beginning.My device is based on sdk12.3, so I deleted the starter setUnsafeExperimentalButtonlessServiceInSecureDfuEnabled (true) and.SetKeepBond (true).

But there is no effect. I am thinking whether there is something wrong with my service by connecting bluetooth. 
If I do other operations at the same time, I cannot upgrade dfu.

**Comment by philips77** [comment]
Hmm,.. yes, that may be related. I've heard that DFU service isn't working with Firebase connection, etc. I can't find this issue now.
In SDK 12.3 you should leave `starter.setUnsafeExperimentalButtonlessServiceInSecureDfuEnabled(true);`, as this service was used for buttonless in SDK 12.x, as written in docs.

**Comment by mshandan** [comment]
I import no. Nordicsemi. Android. Nrftoolbox source code, and test the hardware upgrade process, found that there is no this step in my APP, so I guess I lack what code, what should I do?

![image](https://user-images.githubusercontent.com/45030023/51223812-57230f80-197e-11e9-9b7b-91782d472f6b.png)

**Comment by mshandan** [comment]
If you have time, I hope you can reply to me as soon as possible, I need to solve this problem immediately, thank you for your help！




------------------ 原始邮件 ------------------
发件人: "Aleksander Nowakowski"<notifications@github.com>;
发送时间: 2019年1月15日(星期二) 晚上6:53
收件人: "NordicSemiconductor/Android-DFU-Library"<Android-DFU-Library@noreply.github.com>;
抄送: "邹刚"<1654381733@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [NordicSemiconductor/Android-DFU-Library] How do lower versionsof apps rely on dfu (#160)




Hmm,.. yes, that may be related. I've heard that DFU service isn't working with Firebase connection, etc. I can't find this issue now.
 In SDK 12.3 you should leave starter.setUnsafeExperimentalButtonlessServiceInSecureDfuEnabled(true);, as this service was used for buttonless in SDK 12.x, as written in docs.

**Comment by philips77** [comment]
Hello @mshandan,
Starting the DFU service should be straightforward. The only requirements are adding DfuService as `<service...>` tag to the AndroidManifest and then calling `start(context, DfuService.class)` as you do. To get the detailed logs on LogCat you have to extend `isDebug()` method in your DfuService and return true. Check out here:
https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/9a29921769d775f2ff2dc1276a7062fe0c25c3b7/app/src/main/java/no/nordicsemi/android/nrftoolbox/dfu/DfuService.java#L49

**Comment by mshandan** [comment]
I suddenly thought of a question, my hardware product can run on the latest no. Nordicsemi. Android. Nrftoolbox, is it possible that I failed to upgrade due to the different version of dfu I imported?

**Comment by philips77** [comment]
The DFU library is compatible with all versions of DFU bootloader released by Nordic and even some modifications. Each next DFU library is supposed to have less bugs, but still all are backwards compatible, unless there is a bug. I don't remember which version of DFU Lib is used by the current version of nRF Toolbox, but it's written on the screen.
DFU may fail only if some breaking changes were made in the bootloader/buttonless service, but that's not your case.

**Comment by mshandan** [comment]
I think my problem is that my hardware isn't in dfu mode, so it's problematic to boot directly through DfuService.What do you think?If so, what can I do to get the hardware into dfu mode?

**Comment by philips77** [comment]
If you are using any of the buttonless services that we had in Nordic (first buttonless service was added in SDK 6.1, then it has evolved until get the recent shape) then everything should work automatically. When you start DFU by giving any address, the DFU service will connect to it (the device may already be connected, it doesn't matter, but the service will create its own GATT client to it), will perform service discovery and check what's on the device and, depending on what has been found, will perform DFU or jump to DFU mode using the found service.

**Comment by mshandan** [comment]
Hello, my device can be upgraded with dfu on the NRF toolbox, but that is achieved by clicking the button. Does this mean that it is not feasible for me to use the buttonless service? The hardware is also written according to relevant documents, I am not sure whether there is relevant code of the buttonless service in it.

**Comment by philips77** [comment]
Try connecting to your device with nRF Connect for Android. You will see the device's services there. If Buttonless update is supported you should see there Experimental buttonless service (assuming you are using SDK 12.3).

**Comment by mshandan** [comment]
![image](https://user-images.githubusercontent.com/45030023/53166438-3cdcf100-3610-11e9-9e46-294e2b598465.png)
The last one is support?

**Comment by philips77** [comment]
Yes, that one is supported. You have to call `.setUnsafeExperimentalButtonlessServiceInSecureDfuEnabled(true)`, like here:
https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/9a29921769d775f2ff2dc1276a7062fe0c25c3b7/app/src/main/java/no/nordicsemi/android/nrftoolbox/dfu/DfuActivity.java#L742
and it should work. You may test it by:
1. Enable notifications on the characteristic inside,
2. Write 0x01 to the characteristic.
You should get 0x20-01-01 as return and the device should restart in DFU mode. The notification may not come, but the device should reboot.

**Comment by mshandan** [comment]
Is this test on the Android side?Can I be more specific? Thank you!

**Comment by philips77** [comment]
Yes, just use nRF Connect. After connecting and clicking the Experiments service you should see the Buttonless characteristic with 2 icons on the right. Click the arrows pointing down to enable notifications and then the other one pointing up to send data. There should be a dialog "Do you want to reboot in Bootloader mode?", just select YES an SEND.

**Comment by mshandan** [comment]
According to what you said, I found that the device has been restarted and the device name has changed, but the device in my APP still cannot be upgraded. When the dfu part is executed, the dfu service does not seem to start.

**Comment by philips77** [comment]
Could you post logs fro LogCat here? To get them, return true from `isDebug()` method in your DfuService.

**Comment by mshandan** [comment]
![image](https://user-images.githubusercontent.com/45030023/53216023-24132080-368e-11e9-8eb5-129feb136827.png)
When you say logcat log, do you mean this one?Or a file?Now I don't know if the dfu service is started.

**Comment by philips77** [comment]
Yes, I need the relevant logs from LogCat. You may filter by "dfu".
Did you add your DfuService class to AndroidManifest?

**Comment by mshandan** [comment]
Ok, I initially added the DfuService class to the AndroidManifest, but there is no dfu log associated with it.I used
Intent intent1 = new Intent(controlCenterActivity.this, DfuService.class);
            startService(intent1); 
to force dfuservice on。
Logcat as follows：
02-22 18:39:37.305 15100-15591/com.feijia.alfapreg D/dfu: getNotificationTarget: 
02-22 18:39:37.309 15100-15591/com.feijia.alfapreg E/DfuBaseService: An exception occurred while opening files. Did you set the firmware file?
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.available()' on a null object reference
                                                                         at no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent(DfuBaseService.java:1062)
                                                                         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                         at android.os.Looper.loop(Looper.java:173)
                                                                         at android.os.HandlerThread.run(HandlerThread.java:65)
02-22 18:39:37.309 15100-15591/com.feijia.alfapreg D/dfu: getNotificationTarget: 
02-22 18:39:37.318 15100-15100/com.feijia.alfapreg I/DfuBaseService: DFU service destroyed

**Comment by philips77** [comment]
You have to use the `DfuServiceInitiator` to start DFU, not like you are doing.
You have it described here: https://github.com/NordicSemiconductor/Android-DFU-Library/tree/release/documentation

**Comment by mshandan** [comment]
Sorry, you may not understand what I mean, I mean I wrote everything you said, there is no dfuservice logcat, but if I add that there will be a logcat. 
final DfuServiceInitiator starter = new DfuServiceInitiator(gatt.getDevice().getAddress())
                .setDeviceName(gatt.getDevice().getName())
                .setKeepBond(true);
        starter.setUnsafeExperimentalButtonlessServiceInSecureDfuEnabled(true);
        starter.setZip(R.raw.app2);
        final DfuServiceController controller =starter.start(context,DfuService.class);


        Intent intent1 = new Intent(controlCenterActivity.this, DfuService.class);
        startService(intent1);






------------------ 原始邮件 ------------------
发件人: "Aleksander Nowakowski"<notifications@github.com>;
发送时间: 2019年2月22日(星期五) 晚上9:30
收件人: "NordicSemiconductor/Android-DFU-Library"<Android-DFU-Library@noreply.github.com>;
抄送: "邹刚"<1654381733@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [NordicSemiconductor/Android-DFU-Library] How do lower versionsof apps rely on dfu (#160)




You have to use the DfuServiceInitiator to start DFU, not like you are doing.
 You have it described here: https://github.com/NordicSemiconductor/Android-DFU-Library/tree/release/documentation

**Comment by philips77** [comment]
You should not start DfuService on your own. Initiator will start it. Remove the last 2 lines.

**Comment by mshandan** [comment]
Yes, I know the last two lines are not needed, but Initiator did not start DfuService because I did not see any logs about DfuService.




------------------ 原始邮件 ------------------
发件人: "Aleksander Nowakowski"<notifications@github.com>;
发送时间: 2019年2月24日(星期天) 凌晨3:45
收件人: "NordicSemiconductor/Android-DFU-Library"<Android-DFU-Library@noreply.github.com>;
抄送: "邹刚"<1654381733@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [NordicSemiconductor/Android-DFU-Library] How do lower versionsof apps rely on dfu (#160)




You should not start DfuService on your own. Initiator will start it. Remove the last 2 lines.

**Comment by mshandan** [comment]
I have found the reason why the dfu service is not started. I am very sorry for wasting your time.Below is the logcat：

**Comment by philips77** [comment]
Congratulations, looks like the DFU worked! :)

**Comment by mshandan** [comment]
But I don't think it worked, because the name of the device hasn't changed

**Comment by mshandan** [comment]
There should not be a successful logcat upgrade？

**Comment by mshandan** [comment]
I have posted all my logcat, but I remember that if the dfu upgrade is successful, there will be a successful logcat, and the name of the device will change, but now the device name has not changed, so I feel there is something missing, I will be successful, I hope you can help me, thank you.


------------------ 原始邮件 ------------------
发件人: "Aleksander Nowakowski"<notifications@github.com>;
发送时间: 2019年2月25日(星期一) 下午5:18
收件人: "NordicSemiconductor/Android-DFU-Library"<Android-DFU-Library@noreply.github.com>;
抄送: "邹刚"<1654381733@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [NordicSemiconductor/Android-DFU-Library] How do lower versionsof apps rely on dfu (#160)




Congratulations, looks like the DFU worked! :)

**Comment by philips77** [comment]
Well.. the device name change depends on what you have send as an update. If it's the same fw as was already running, nothing will change.
In LogCat success is when you don't get any error. Also, you got: `Transfer of 32976 bytes has taken 8878 ms.`.

**Comment by mshandan** [comment]
The hardware told me that the name of the device will change after the successful upgrade. The upgrade time has been over 8 seconds. I think there must be some mistake.
