### ISSUE TITLE
Transfer is stopped when sending data.

### ISSUE THREAD

**Issue by yogiohkid** [NordicSemiconductor/Android-DFU-Library#17]
When I used the DFU to upgrading the firmware.The process before the transmission of Firmware packets is all normal.But,When Firmware packet being transmitted , progress will be stuck in such as 7% or 53% or 93%.This problem only occurs on my device,My Device is Samsung S7 Edge, Android 6.0.1.But when I use the nRF tools,this problem doesn‘t exist.

**Comment by zzkggmy** [comment]
> When I used the DFU to upgrading the firmware.The process before the transmission of Firmware packets is all normal.But,When Firmware packet being transmitted , progress will be stuck in such as 7% or 53% or 93%.This problem only occurs on my device,My Device is Samsung S7 Edge, Android 6.0.1.But when I use the nRF tools,this problem doesn‘t exist.

Hello  How do you solution this,I have same problem(你好，请问这个问你你是怎么解决的 我也遇到了相同的进度卡死的问题)
