### ISSUE TITLE
How do dfu upgrades use zip on the server 

### ISSUE THREAD

**Issue by mshandan** [NordicSemiconductor/Android-DFU-Library#171]
How do dfu upgrades use zip on the server or use zip downloaded from the server

**Comment by philips77** [comment]
Hello,
You may download the ZIP on your own, for example using Retrofit, save it in app's storage and pass Path or URI to this file to the `DfuServiceInitiator`. The DFU service expects the file as resource id, or a stream given as path or URI. There isn't an option to just pass the bytes as an array, at least in the current version.

**Comment by E3V3A** [comment]
Where and what is *Retrofit*?

**Comment by philips77** [comment]
https://square.github.io/retrofit/

**Comment by E3V3A** [comment]
I see. 
https://github.com/square/retrofit

But that is just the protocol and not where to find the actual files.

**Comment by mshandan** [comment]
Do you want to download the file from the server and use it？

**Comment by E3V3A** [comment]
Yes. In fact that's what I was hoping (and thought) the app would do for you, automatically.
(How else would I get the correct zip file onto the phone?)

**Comment by philips77** [comment]
nRF Toolbox allows you to select the file using any File Browser app, not necessarily from the phone's External Storage. You may use Google Drive, Microsoft One, etc. They are available in the navigation menu of the default file chooser (since KitKat).
