### ISSUE TITLE
Add option to remove abort button from notification

### ISSUE THREAD

**Issue by marcbaldwin** [NordicSemiconductor/Android-DFU-Library#180]
Is it possible to add an option to remove the **Abort** button from the notification?

**Comment by philips77** [comment]
In your `DfuService` class you may override the `updateProgressNotification` method. By default it adds the Abort action.
https://github.com/NordicSemiconductor/Android-DFU-Library/blob/ec14c8c522bebe801a9a4c3dfbbeb1f53262c03f/dfu/src/main/java/no/nordicsemi/android/dfu/DfuBaseService.java#L1720-L1733

**Comment by marcbaldwin** [comment]
Thanks 👍
