### ISSUE TITLE
dfubaseservice: connected. dfu service not found

### ISSUE THREAD

**Issue by M-k-03** [NordicSemiconductor/Android-DFU-Library#183]
Hi Team,

I am trying to connect and update my Bluetooth Device using this library. 

when i checked through logs below mentioned error happens and device getting disconnected.
[DfuBaseService.java]
dfubaseservice: connected. dfu service not found.

I would like to know why this error is happening.  Kindly Guide me

**Comment by philips77** [comment]
Hello,
Do you have the DFU service on your device? Try connecting to it using nRF Connect for Android and see if the Legacy or Secure DFU service are there.

**Comment by M-k-03** [comment]
![IMG_20190508_153241](https://user-images.githubusercontent.com/15815453/57367655-0a6e7900-71a7-11e9-9c60-fb51d3da9fe6.JPG)

Hi sorry for delayed response. I connected with nRf connect for Android.. Legacy..

**Comment by M-k-03** [comment]
![DFU-1](https://user-images.githubusercontent.com/15815453/57575375-ce693b80-7466-11e9-9578-ef05c9b2a311.jpeg)
![DFU-2](https://user-images.githubusercontent.com/15815453/57575379-d5904980-7466-11e9-9186-e31aa7aff3bf.jpeg)


Hi After Connecting using nRF Connect with my band mentioned above service listed. :( still i cant find Legacy or Secure DFU

**Comment by philips77** [comment]
Well, that's because your device doesn't support Dfu. Please, go to the documentation on our website to find out how to make it up and running.

**Comment by M-k-03** [comment]
Hi My device does not support dfu now as you mentioned. 
I have few questions regarding this.

1: Is it possible to make my device dfu compatible. If yes please provide the link so that I can proceed further.
