### ISSUE TITLE
Connect to BL with incremented mac address

### ISSUE THREAD

**Issue by kinber95** [NordicSemiconductor/Android-DFU-Library#203]
Hi,

currently we working on a new firmware version to get ride of the bonding stuff from Android, because it causes too much issues. But now we struggle a little bit with the new firmware update. 
When we set the device in the BL mode it appears with the new incremented mac address and we have to reconnect to it. But the library still wants to reconnect to the device with the "old" mac address. We found in the library the BootloaderScanner what should handle this use case. 

So is this is a bug or do we need todo some more interactions in the dfu process ? 

Currently we only initialized the DfuServiceInitiator with the "old" mac address and handle some UI changes in with the DfuProgressListener. With the bond versions from Android we had no problems.

**Comment by philips77** [comment]
If you want your new version to be without bonding, you need to modify the dfu library on your own. You'll have to first flash the new bootloader, that will not use bonding, and will use a new address after rebooting. Than, update the app, which should also increment on change the address, so the bond information became irrelevant. These are all new features, and it's expected not to work with the library as is.
