### ISSUE TITLE
Custom title, message and icon for foreground notification?

### ISSUE THREAD

**Issue by cheeyi** [NordicSemiconductor/Android-DFU-Library#204]
Hello, is there a way to specify a custom title, message and icon for the foreground notification that is shown when a firmware update is in process? Thank you.

**Comment by philips77** [comment]
There's a method in BaseDfuService that you can override in you service to modify the notification.

**Comment by cheeyi** [comment]
> There's a method in BaseDfuService that you can override in you service to modify the notification.

@philips77 Is `updateProgressNotification()` the method you were referring to? Or is it `updateForegroundNotification()`? Thanks in advance.

**Comment by philips77** [comment]
Well... The names are self explanatory. Remember that you may disable the default progress notifications, or start dfu in background, not foreground. Appropriate methods are in the initiator.

**Comment by cheeyi** [comment]
Thanks @philips77 for your kind help and explanation! Closing this issue.
