### ISSUE TITLE
DFU mode connect not work

### ISSUE THREAD

**Issue by Hugo-Hyenatek** [NordicSemiconductor/Android-DFU-Library#210]
Hi, some phones have DFU update problem, device stopped at connection moment.

Tested smartphone:
1. Huawei Y7 Prime 2018, Android OS 8.0.0
2. ASUS Z00UD, Android OS 6.0.1

DfuBaseService logs:
```
I/DfuBaseService: DFU service created. Version: 1.9.0
W/DfuBaseService: Foreground service disabled. Android Oreo or newer may kill a background service few moments after user closes the application. Consider enabling foreground service using DfuServiceInitiator#setForeground(boolean)
I/DfuBaseService: Connecting to the device...
```
wait few minutes nothing happened!

**Comment by philips77** [comment]
Make sure the devices are advertising and are connectable. Try DFU them using nRF Connect on those phones and send us the log from this app.

**Comment by Hugo-Hyenatek** [comment]
Sorry, this time to reply.

Every time open the nRF Connect app for the first time, still stuck during connection.
**log only:**[Server] server started

After disconnection, then it can be used normally work after the second connection.
