### ISSUE TITLE
Not getting DFU Progress

### ISSUE THREAD

**Issue by Nits2407** [NordicSemiconductor/Android-DFU-Library#211]
I am unable to get DFU Progress status broadcast

**Comment by philips77** [comment]
Are you using the [DfuServiceListenerHelper](https://github.com/NordicSemiconductor/Android-DFU-Library/blob/release/dfu/src/main/java/no/nordicsemi/android/dfu/DfuServiceListenerHelper.java) and you have registered it using 
https://github.com/NordicSemiconductor/Android-DFU-Library/blob/58bd4c2aec66b85e779d8be7d6e05ca8a47cb1ed/dfu/src/main/java/no/nordicsemi/android/dfu/DfuServiceListenerHelper.java#L285
This is using the `LocalBroadcastManager` so only your app (the same process) can receive the updates.
