### ISSUE TITLE
DFU FILE ERROR

### ISSUE THREAD

**Issue by yisiang** [NordicSemiconductor/Android-DFU-Library#237]
**DFU Bootloader version (please complete the following information):**
 - SDK version: Unknown
 - Bonding used: no
 - Library version: 1.10.2

**Device information (please complete the following information):**
 - Device:Huawei Honor 10
 - OS: Android 10

**Describe the bug** </br>

I have a zip file, the files inside are as shown:
![2020-05-23 20-04-14 的螢幕擷圖](https://user-images.githubusercontent.com/18330683/82730208-af1b1480-9d30-11ea-8e11-d3fc8561330d.png)
![2020-05-23 20-04-22 的螢幕擷圖](https://user-images.githubusercontent.com/18330683/82730209-b2160500-9d30-11ea-95d7-479b0ce533e3.png)

I wrote the code：
```kotlin
val controller = DfuServiceInitiator(bleAddress)
            .setPrepareDataObjectDelay(400L)
            .setUnsafeExperimentalButtonlessServiceInSecureDfuEnabled(true)
            .setZip(R.raw.trainer-firmware)
            .start(this, DfuService::class.java)
```

It can be executed normally in version 1.10.1, but DFU FILE ERROR will appear in version 1.10.2
</br>
I found that after calling `validateFilename()` in the `ArchiveInputStream`, the manifest file name becomes `/manifest.json`, so it is never equal to the `MANIFEST` constant value `manisfest.json`, the bin and dat file names are` /trainer-firmeare.bin` `/trainer-firmware.dat` and bin_file: `trainer-firmware.bin` dat_file: `trainer-firmware.dat` in manifest.json is not the same

**Comment by philips77** [comment]
Fixed in 1.10.3. Thank you for your bug report!
