### ISSUE TITLE
4096problem

### ISSUE THREAD

**Issue by kdwu** [NordicSemiconductor/Android-DFU-Library#241]
when i use this library to upgrade the bluetooth， sometimes 4096 error will be thrown。and this problem will appear on Google phone pixel 3a XL sometime。

**Comment by philips77** [comment]
Please, share your logs. 4096 just means disconnection.

**Comment by philips77** [comment]
4096 = 0x1000 which is the 
https://github.com/NordicSemiconductor/Android-DFU-Library/blob/2f61019d6da350ce3e577b5115e82b727b1c7112/dfu/src/main/java/no/nordicsemi/android/dfu/DfuBaseService.java#L575
