### ISSUE TITLE
4109problem

### ISSUE THREAD

**Issue by kdwu** [NordicSemiconductor/Android-DFU-Library#243]
when i use this library to upgrade the bluetooth， sometimes 4109 error will be thrown。and this problem will appear on Google phone pixel 3a XL everytime。

**Comment by philips77** [comment]
4109 = 0x100D which indicates it's `ERROR_CRC_ERROR`:
https://github.com/NordicSemiconductor/Android-DFU-Library/blob/2f61019d6da350ce3e577b5115e82b727b1c7112/dfu/src/main/java/no/nordicsemi/android/dfu/DfuBaseService.java#L621-L625
