### ISSUE TITLE
error : 133, message :GATT ERROR 

### ISSUE THREAD

**Issue by harishankar-jayasakthi** [NordicSemiconductor/Android-DFU-Library#244]
Hello, I have the facing this error always on this device only, but it is working good in other devices
 
 Device OS version: 9
 App Version: 1.12
 Device Brand: HONOR
 Device Model: LLD-AL20
 Device Manufacturer: HUAWEI

dfu : onError 
**error : 133, type :1, message :GATT ERROR** 

Any solution for this issue?

**Comment by philips77** [comment]
This may be an issue with the BLE controller on your Huawei. I don't think much can be done about it. You'd have to sniff the connection and debug the problem. A fix, most probably, will have to be implemented on the DFU target side.
133 is a generic error for BLE on Android and does not specify a reason.
