### ISSUE TITLE
shutdown device after failed DFU

### ISSUE THREAD

**Issue by Tychus** [NordicSemiconductor/Android-DFU-Library#27]
Is there any way to reboot the device after a failed dfu operation from my end ? i've seen this somewhere deep in the code "legacyDfuImpl.java" was wondering if i can do this from the controller or any other way.

**Comment by philips77** [comment]
Hi, the service should aromatically reset the device with legacy DFU in case of error. There is no way to just reset it as a separate function. Hoverer, you may do this on your own by sending Reset 0x06(?) command to the control point, after ensuring that notifications are enabled.

**Comment by Tychus** [comment]
yeah took a look at the code but it happened once got file error and device remained in DFU mode.
