### ISSUE TITLE
 Android 10 DFU update cannot be performed

### ISSUE THREAD

**Issue by alphaYuto** [NordicSemiconductor/Android-DFU-Library#270]
**Information**
This GitHub Issue page is for reporting issues or asking questions regarding the iOS DFU library. For general DFU questions, SDK questions, etc, please check our [DevZone](https://devzone.nordicsemi.com/).
Make sure you are using the latest version of the library: [ ![Download](https://api.bintray.com/packages/nordic/android/no.nordicsemi.android%3Adfu/images/download.svg) ](https://bintray.com/nordic/android/no.nordicsemi.android%3Adfu/_latestVersion)
Also, before creating a new issue, make sure similar issue isn't already opened in [open](https://github.com/NordicSemiconductor/Android-DFU-Library/issues) or [closed](https://github.com/NordicSemiconductor/Android-DFU-Library/issues?q=is%3Aissue+is%3Aclosed) issues.

**DFU Bootloader version (please complete the following information):**
 - SDK version:
 - Bonding used: no
 - Library version: 1.11.0

**Device information (please complete the following information):**
 - Device: Sony Xperia SO03K Android10
 - OS: Android10

**Your question**
Hello
I implemented the DFU update to Android 6.0 before, but when I migrated to Android 10 this time, the DFU update was not possible and an error occurred. The error content is "Invalid notification of start of foreground". Is there any solution?

**Logs**
Add any other context or logs describing the problem here.
[20200903_DFU error.txt](https://github.com/NordicSemiconductor/Android-DFU-Library/files/5173167/20200903_DFU.error.txt)

**Comment by philips77** [comment]
> Also, before creating a new issue, make sure similar issue isn't already opened in open or closed issues.

Have a look at #266.
