### ISSUE TITLE
Can not import the library as a module due to gradle-bintray-push file broken reference

### ISSUE THREAD

**Issue by OlgaDery** [NordicSemiconductor/Android-DFU-Library#273]
Hello,
I have tried to import the library to my Android project following the steps described in the documentation here - https://github.com/NordicSemiconductor/Android-DFU-Library/tree/release/documentation. It failed to build due to the following error - "Could not read script '/Users/olgadery/AndroidStudioProjects/orpyxbluetoothsdk/gradle/gradle-bintray-push.gradle' as it does not exist." Looks like this file is located in the "gradle" folder that is not being imported if I am following the listed steps.
Are there any ways to fix this issue? Thanks in advance.

**Comment by philips77** [comment]
Comment this line out.

**Comment by OlgaDery** [comment]
Works, thanks a lot.
