### ISSUE TITLE
Request Demo Code of Implementing DFU library.

### ISSUE THREAD

**Issue by VinayTShetty** [NordicSemiconductor/Android-DFU-Library#286]
Hi thanks for providing such a good resources.
But i am not able to find out how to use the DFU library and make the DFU update.
I am getting half lesson from the [link](https://github.com/NordicSemiconductor/Android-DFU-Library/tree/release/documentation)
Any example implementation of DFU library code is avaliable means it would be helpfull

**Comment by philips77** [comment]
Hello,
We do have a sample in [nRF Toolbox](https://github.com/NordicSemiconductor/Android-nRF-Toolbox/tree/master/app/src/main/java/no/nordicsemi/android/nrftoolbox/dfu). The app is quite complex, as there are different profiles, but if you'd check only DFU it's just few classes.
