### ISSUE TITLE
Is the protocol documented?

### ISSUE THREAD

**Issue by richorama** [NordicSemiconductor/Android-DFU-Library#299]
**Device information (please complete the following information):**
 - Chrome on Windows 10

**Your question**

Hi, I have had some success connecting to the nordic board using the [Bluetooth Web API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API) on Windows 10 using Chrome/Edge. This presents an excellent opportunity for our product, as no android software installation would be required to do a DFU.

I am able to access the DFU characteristic, and I can open the zip file, read the manifest and extract the bin/dat files.

I have been trying to pick through this source code to understand how the files are uploaded, over the BLE characteristic, but I'm finding the code hard to understand. Is there a description in English of how the DFU protocol works?

Thank you for your help.

**Comment by philips77** [comment]
Hello,
You may find the Secure DFU protocol documented here: https://infocenter.nordicsemi.com/topic/sdk_nrf5_v17.0.2/lib_dfu_transport.html?cp=7_1_3_5_2
At the bottom there's a link to BLE transport layer documentation as well.

The Legacy DFU is documented in SDK 11.0: https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.sdk5.v11.0.0/examples_ble_dfu.html?cp=7_5_12_4_3_1
