### ISSUE TITLE
Duplicate class android support library.

### ISSUE THREAD

**Issue by bingerz** [NordicSemiconductor/Android-DFU-Library#307]
Our company's customers use Android-DFU-Library and encounter the following error:
```
Duplicate class android.support.v4.app.INotificationSideChannel found in modules core-1.5.0-alpha01-runtime.jar (androidx.core:core:1.5.0-alpha01) and support-v4-23.4.0-runtime.jar (com.android.support:support-v4:23.4.0)
```
Android IDE: **Eclipse**

Their project does not enable AndroidX, and the project relies on `com.android.support:support-v4:23.4.0`. In this case, is there any good way to avoid this conflict without changing the client project’s dependency library?

**Comment by philips77** [comment]
Latest version of this library not migrated to AndroidX is 1.8.1.

**Comment by bingerz** [comment]
> Latest version of this library not migrated to AndroidX is 1.8.1.

Thank you.
