### ISSUE TITLE
FOTA

### ISSUE THREAD

**Issue by kcjian** [NordicSemiconductor/Android-DFU-Library#308]
Hello，How can my own app realize FOTA function？

[FOTA](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/ug_nrf5340.html#fota-upgrades)

**Comment by philips77** [comment]
For FOTA based on NCS use https://github.com/JuulLabs-OSS/mcumgr-android instead of this library.

**Comment by trusbe** [comment]
It is recommended to update to the README page of the DFU project.
