### ISSUE TITLE
app是target30,手机是android12 时, 新版本1.12.0有权限问题

### ISSUE THREAD

**Issue by qigithub** [NordicSemiconductor/Android-DFU-Library#323]
**Information**

**DFU Bootloader version (please complete the following information):**
 - APP TargetSdk version: 30
 - Bonding used: [no]
 - Library version: [ 1.12.0]

**Device information (please complete the following information):**
 - Device: [xiaomi 11]
 - OS: [Android 12 ,miui 13]

**Describe the bug**
app是 target30,手机是android12 时, 新版本nordicLib 有权限问题,BLUETOOTH_SCAN和 BLUETOOTH_CONNECT权限是TargetSDK31才需要申请的,小于31时,还是需要旧的蓝牙权限, 所以当target30 不应该申请 BLUETOOTH_SCAN和 BLUETOOTH_CONNECT

**Logs**
Add any other context or logs describing the problem here.

**Comment by philips77** [comment]
The new version should request correct permissions.
