### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by ap8866** [NordicSemiconductor/Android-DFU-Library#324]
Hello,

I tried checking out the main and develop branch of the project. Still getting these errors, please check the attached image.

Any help is really appriciated.
![dfu error](https://user-images.githubusercontent.com/53778604/157039194-63a79e88-bfbb-476c-9fc3-d290fd258d14.PNG)

**Comment by ap8866** [comment]
Thank you so much for your response!

My dependencies looks like:
dependencies {
    implementation 'androidx.core:core:1.7.0'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'
    implementation 'androidx.annotation:annotation:1.2.0'
    implementation 'no.nordicsemi.android:dfu:1.12.1-beta01'
    implementation 'com.google.code.gson:gson:2.8.8'
}

I also get a different error in the main branch, please have a look at the attached image
![main_branch](https://user-images.githubusercontent.com/53778604/157175591-164c3e57-b95a-4fdd-94bf-08a035bd62e7.PNG)
.

**Comment by philips77** [comment]
Hi, did you try after latest updates?
