### ISSUE TITLE
Taks: Make the initial delays in connection optional

### ISSUE THREAD

**Issue by philips77** [NordicSemiconductor/Android-DFU-Library#329]
The DFU service has some artificial delays, added at some points in the history, e.g.:
https://github.com/NordicSemiconductor/Android-DFU-Library/blob/9d953c0fc3e082a94279b2b792749ebbf3f8e528/lib_dfu/src/main/java/no/nordicsemi/android/dfu/DfuBaseService.java#L1285-L1290
which were added to improve connection stability. They may not be required on mored phones or latest Android versions.

Task:
- [ ] Remove the `waitFor` callas and check it DFU still works.
- [ ] Test on different phones with older Android versions, compare behavior.
- [ ] If they seem to be needed, make the `waitFor` optional in the DFU initializer (leaving enabled by default for backwards compatibility), or remove them in the initial connection, leaving only for the retries.

**Comment by philips77** [comment]
This issue is to solve #328.

**Comment by obasille** [comment]
Hi! Thanks for creating this issue, is it something that you think will be look at in the near future?

**Comment by philips77** [comment]
Yes, that is the plan. Also, depends on the definition of "near future".
