### ISSUE TITLE
Does not support .bin?

### ISSUE THREAD

**Issue by rayzeng0221** [NordicSemiconductor/Android-DFU-Library#352]
Does the DFU app support BIN files?

**Comment by philips77** [comment]
Let me reply with some background information.

There are now 3 non-compatible with each other protocols for Device Firmware Update (DFU) which can be used for updating over the air Nordic devices:
* Legacy DFU
* Secure DFU
* DFU based on McuManager and Simple Management Protocol (SMP)

This application (DFU) supports the first 2: Legacy and Secure DFU. Those protocols are compatible with [nRF5 SDK](https://infocenter.nordicsemi.com/topic/struct_sdk/struct/sdk_nrf5_latest.html?cp=8_1). Legacy DFU was added in SDK 4.3 and lasted until SDK 11, Secure DFU was added in SDK 12 and become deprecated together with nRF5 SDK. It is still supported for existing solutions, but for new designs nRF Connect SDK is recommended with its DFU based on McuManager also know as nRF Connect Device Manager.
The last method is supported by [nRF Connect Device Manager](https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfconnectdevicemanager) or [nRF Connect for Mobile](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp) apps.
In nRF5 SDK the firmware was split into 3 parts: 
* Soft Device - a stack delivered by Nordic
* Bootloader - the bootloader for updating the firmware
* Application - developed by users using the Soft Device.

Both Legacy and Secure DFU allow updating any set of those 3, but a BIN file is not enough, as user needs to provide a DAT file (with metadata, signature, hw and fw requiremens) and, for Legacy DFU, also the type of the BIN (is it an update for the App, Soft Device, or a Bootloader. Also, it is not possible to update together the Soft Device and Bootloader by having only the BIN and DAT files in Legacy DFU, as the SD and BL sizes are provided outside of DAT file.

For that reason, the [*nrfutil*](https://github.com/NordicSemiconductor/pc-nrfutil) tool generates ZIP packages with additional *manifest.json* file containing all required information. The DFU application accepts currently only ZIP files generated using this tool. If you want to use only BIN and DAT file, and provide the fw type manually, use nRF Connect for Mobile app.

> Note:
   If your firmware is based on nRF Connect SDK (NCS), use any of the apps mentioned above: nRF Connect Device Manager or nRF Connect for Mobile. There, for single core devices, it is enough to have a signed BIN file, as it contains the metadata needed for the update.
