### ISSUE TITLE
core library error

### ISSUE THREAD

**Issue by hunter-newpeak** [NordicSemiconductor/Android-DFU-Library#355]
trying to build or sync the current commit (af59adcc5ad9f4488b615f76c500039e967beb51) in android studio results in an error:
`Failed to resolve: no.nordicsemi.android.common:core:1.0.21`

**Comment by philips77** [comment]
I will release the version today, sorry for that.
I was too quick with pushing my changes to `main`.

**Comment by philips77** [comment]
Fixed with core lib version 1.0.22 and DFU 2.2.
