### ISSUE TITLE
Nordic Uart services integration in  Android DFU Library Source Code:

### ISSUE THREAD

**Issue by inamghouss** [NordicSemiconductor/Android-DFU-Library#368]
Hi,
I just compiled and ran this source code on my device and it is working fine.
I am also able to modify some of its small parameters like icon, name, etc.
Now the issue is I want to add nus services in this app(just too visible one characteristic in the app). I am new in java/App development but had a good experience in programming(embedded-c and python). Can you suggest any tutorials/Videos to understand this source code? so that I can implement modifications according to my application.
Any advice would be appreciated.
Thanks for your time.

**Comment by philips77** [comment]
Sorry, there's no documentation for the nRF DFU app, but the code isn't complex. It's a small app, created mainly as a sample.
Good luck with your project.
