### ISSUE TITLE
mobile phone compatible

### ISSUE THREAD

**Issue by hjjice** [NordicSemiconductor/Android-DFU-Library#385]
### Information
Hello, can you be compatible with Xiaomi mobile phones or Redmi mobile phones? Xiaomi mobile phones basically have the phenomenon that 255 cannot be upgraded. The version of my DFU library is 2.3.0.

### Logs
An error occurred while connecting to the device: 255

**Comment by hjjice** [comment]
I found a magical phenomenon. DFU Cuolian is not connected to the device. At this time, exit the APP, use NRF to connect to the device in DFU mode, and then upgrade with my app to upgrade

**Comment by obasille** [comment]
Sorry to hear you're having trouble. I'm using the DFU library 2.1.0 and the lastest DFU app (2.3.0) on my Xiaomi phone without issue.

**Comment by hjjice** [comment]
> Sorry to hear you're having trouble. I'm using the DFU library 2.1.0 and the lastest DFU app (2.3.0) on my Xiaomi phone without issue.

What about Redmi?

**Comment by voctex** [comment]
> Sorry to hear you're having trouble. I'm using the DFU library 2.1.0 and the lastest DFU app (2.3.0) on my Xiaomi phone without issue.

My Xiaomi 8 phone never had an issue with upgrading, but on my Xiaomi 10, there was a problem with upgrading. The Android version is 12 and the DFU library version used is 2.3.0.

**Comment by Brontes** [comment]
I had similar problems (also with some other phones, not just on Xiaomi)

My device changes MAC when it goes to DFU mode.

If I wanted to start update immediately after I put device into DFU it was unsuccessful. I received:

"
Connection state change error: 133 newState: 0
Device not reachable. Check if the device with address xxx is in range, is advertising and is connectable
"

I found out that I have to wait the device to start advertising with new MAC. After that I could start update without any problems library.

**Comment by philips77** [comment]
I'll fix the Redmi issue tomorrow.

**Comment by philips77** [comment]
The Redmi scanning issue should be now fixed with #403.
