### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by nachtien** [NordicSemiconductor/Android-DFU-Library#39]
Hi there!

I'm curious what changes were in these different versions.  Is there anyway the release notes could be updated, or create a change log?  It would be super helpful.  

https://github.com/NordicSemiconductor/Android-DFU-Library/releases

Thanks,
Nick

**Comment by philips77** [comment]
Hi, sorry. I forgot to publish change log of some updates. Yesterday I published version 1.2.0 and you will find a release there.
I hope this will not happen again.

**Comment by nachtien** [comment]
Great thanks!
