### ISSUE TITLE
Importing source code showing error

### ISSUE THREAD

**Issue by Ashwin-Sqt** [NordicSemiconductor/Android-DFU-Library#390]
### Your question
Importing the source code getting this error . An help will be appreciated

### Logs
No matching variant of no.nordicsemi.android.gradle:plugins:1.4.2 was found. The consumer was configured to find a library for use during runtime, compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.1.1' 

![image](https://github.com/NordicSemiconductor/Android-DFU-Library/assets/60970374/7578ddaf-5f5e-4dfc-b608-949374891013)

**Comment by Ashwin-Sqt** [comment]
Is there any sample app to refer ?

**Comment by rodrigosimoesrosa** [comment]
I've solved it with the new android studio flamingo version and changing via Jenv the Java version to 17.

**Comment by philips77** [comment]
Fixed with #402. Should work on Android Studio Giraffe.
