### ISSUE TITLE
Can you remove android:maxSdkVersion="30"?

### ISSUE THREAD

**Issue by rabingogo** [NordicSemiconductor/Android-DFU-Library#393]
The configuration `android:maxSdkVersion="30"`  in */lib/dfu/src/main/AndroidManifest.xml* is blocking us to upload APP with DFU feature to Google Play, which is requiring minSDK to be "31".

Can you help?

**Comment by philips77** [comment]
This is very interesting. I'll try and remove the old permissions from the manifest if needed.

**Comment by philips77** [comment]
Sorry, I don't understand. Is the `minSdk` requirement in your app, or on Google Play? Google Play may have a requirement for `targetSdk`, not minimum.

Also, the manifest merging should work automatically.
