### ISSUE TITLE
This belongs in a public maven repository.

### ISSUE THREAD

**Issue by eliotstock** [NordicSemiconductor/Android-DFU-Library#4]
We should be able to add this to an existing gradle build with a single dependency.

**Comment by philips77** [comment]
I agree. I'll try to export it in the nearest future. I've assumed that final products may require some changes in the implementation.

**Comment by eliotstock** [comment]
Awesome, thanks.

**Comment by hrldcpr** [comment]
:+1:

**Comment by philips77** [comment]
Done. Lib has been released on jcenter and Maven Central.

[ ![Download](https://api.bintray.com/packages/nordic/android/dfu-library/images/download.svg) ](https://bintray.com/nordic/android/dfu-library/_latestVersion)

**Comment by hrldcpr** [comment]
:clap: works perfectly, thanks!
