### ISSUE TITLE
Unable to use version 2.3.1 with Unity due to Java 17 not being supported.

### ISSUE THREAD

**Issue by PorcelainBear** [NordicSemiconductor/Android-DFU-Library#411]
### Where do you suspect the issue?

Other

### Version

2.3.1 (Latest)

### Describe the issue

Version 2.3.1 is built using (the newly supported) version 61 of Java (Java 17) while the maximum supported version by the Unity game engine is version 55 (Java 11).

We ran into some problems when targeting API Level 34 on Android, getting crashes on Android 14 because:
`One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts`

As I understand the newest update addresses this but we are unable to update as it's not compatible with Unity. Now we aren't sure exactly what causes this error, as we have more than one Java library in the Unity project and identifying which of them might be causing this has been a bit hard. Explanations from google on how to setup one's project to accommodate this new requirement are also non existent so far for Unity projects.

 I just wanted to poke my head in here with this problem and see if it's something that might be fixable in the near future.

**Comment by philips77** [comment]
I can revert to Java 11.
I already did it with [nRF Connect Device Manager](https://github.com/NordicSemiconductor/Android-nRF-Connect-Device-Manager/pull/114) library.

**Comment by PorcelainBear** [comment]
That would be fantastic thank you!
