### ISSUE TITLE
Android 14 GATT 133 1

### ISSUE THREAD

**Issue by MarioTheGreatest** [NordicSemiconductor/Android-DFU-Library#441]
### Where do you suspect the issue?

Issue related to Android version or specific device

### Version

2.4.1 (Latest)

### Describe the issue

![image](https://github.com/NordicSemiconductor/Android-DFU-Library/assets/166128209/21136ee2-7687-4e9a-90e6-249963e359f9)

On Android bellow 14 the DFU library uploads the firmware as expected, but on Android 14 for some reason it will make 3 attempts while stuck on onDeviceConnecting and then return GATT Error 133 1. I have tried disableMtuRequest() and setPacketsReceiptNotificationsValue(1) but it doesn't fix the issue.

**Comment by sumitemizentech** [comment]
I am having similar issue on android 14, Samsung phone. After 3% it throws an error - GATT INVALID PDU.

**Comment by SEAbdulbasit** [comment]
Same issue
`Connection state change error: 133 newState: 0`
` An error occurred while connecting to the device: 133`

**Comment by SEAbdulbasit** [comment]
When i pair first and then try to update the firmware then it works fine.

**Comment by christian-zs** [comment]
I have the same problem here. I need to apply for the dynamic permission ACCESS_FINE_LOCATION. After applying, it's done.

**Comment by christian-zs** [comment]
> ### Where do you suspect the issue?
> Issue related to Android version or specific device
> 
> ### Version
> 2.4.1 (Latest)
> 
> ### Describe the issue
> ![image](https://private-user-images.githubusercontent.com/166128209/319982453-21136ee2-7687-4e9a-90e6-249963e359f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjExNTIsIm5iZiI6MTcyNDY2MDg1MiwicGF0aCI6Ii8xNjYxMjgyMDkvMzE5OTgyNDUzLTIxMTM2ZWUyLTc2ODctNGU5YS05MGU2LTI0OTk2M2UzNTlmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwODI3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmE2ZDA3ZTQ0MjM2NzI5NzEwZjUxN2JjMDBlMzE5MWI0MjFkOTE4OGNiYTBiYzM3YjQ4YTkxYjg0MzM0MjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3NyTQyESkYuYj5PX1spkmE6uDAGcvEPQPVSLxAYJzIM)
> 
> On Android bellow 14 the DFU library uploads the firmware as expected, but on Android 14 for some reason it will make 3 attempts while stuck on onDeviceConnecting and then return GATT Error 133 1. I have tried disableMtuRequest() and setPacketsReceiptNotificationsValue(1) but it doesn't fix the issue.
> 
> ### Relevant log output
> _No response_
I have the same problem here. I need to apply for the dynamic permission ACCESS_FINE_LOCATION. After applying, it's done.

**Comment by philips77** [comment]
Hello,
Last week we released version 2.6, which should fix scanning in background. Did you try it?

As it appears only in background, I suspect it's related to scanning without a `ScanFilter` (or actually, with an empty one). Recent Android versions began to check if the filter isn't empty. In that case the phone doesn't scan and in result cannot connect to the device advertising with address +1.

Since 2.6 the filters are no longer empty and you may customize them using:
https://github.com/NordicSemiconductor/Android-DFU-Library/blob/4123bdd5f20c5f8a1a51cb61546b4fc132513dec/lib/dfu/src/main/java/no/nordicsemi/android/dfu/DfuBaseService.java#L1987-L1990
