### ISSUE TITLE
GATT ERROR on Realme C33

### ISSUE THREAD

**Issue by terrence1991** [NordicSemiconductor/Android-DFU-Library#445]
### Where do you suspect the issue?

Issue related to Android version or specific device

### Version

2.4.1 (Latest)

### Describe the issue

I am an employee of an IoT device company. The company's latest device has received a lot of feedback from customers that it cannot update the firmware. After investigation, it was found that some mobile phone models have been failing. So the company specially purchased a realme c33 mobile phone. Through debugging, it was found that this phone will update its own mtu when transmitting packets in the bootloader state. After commenting the call of the requestMtu method, this phone can update the firmware. I want to confirm whether the requestMtu operation is necessary? I have not found a way to cancel this operation.
![img_v3_02c0_22f2f8af-3458-43f6-8091-543b485382eg](https://github.com/NordicSemiconductor/Android-DFU-Library/assets/3390314/83b5a648-4420-4063-b42f-e27b15e1fba4)

**Comment by philips77** [comment]
> I have not found a way to cancel this operation.

Here you are:
https://github.com/NordicSemiconductor/Android-DFU-Library/blob/b0116a7c6497c9f9c407ec8cfb5534c0b26da11e/lib/dfu/src/main/java/no/nordicsemi/android/dfu/DfuServiceInitiator.java#L426-L435
