### ISSUE TITLE
Android 14 service problem

### ISSUE THREAD

**Issue by pgitsov** [NordicSemiconductor/Android-DFU-Library#448]
DFU 2.3.0 works fine in my app on Android 13, but on Android 14 I get

java.lang.RuntimeException: Unable to create service ...: java.lang.SecurityException: ...: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

Please help!

**Comment by Wichnator** [comment]
You have to update at least to 2.4.0 to fix this issue.
