### ISSUE TITLE
(Crash) DfuServiceListenerHelper.registerProgressListener does not set RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED

### ISSUE THREAD

**Issue by srenrd** [NordicSemiconductor/Android-DFU-Library#450]
### Version

2.5.0

### Describe the issue

DfuServiceListenerHelper.registerProgressListener does not set RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTEDwhich results in a crash for Android 14 and above

**Comment by philips77** [comment]
Hello,
It indeed registers a broadcast receiver, but in the `LocalBroadcastReceiver`, which is local in the app. It does not have this new `exported` parameter.
