### ISSUE TITLE
 DFU CHARACTERISTICS NOT FOUND 

### ISSUE THREAD

**Issue by faisalm70033** [NordicSemiconductor/Android-DFU-Library#454]
### Version

None

### Ask the question
```c#
    const result = await NordicDFU.startDFU({
        deviceAddress: deviceId,
        deviceName: deviceName,
        filePath: actualFilePath,
    })
    .then((afterResult)=>{
        console.log("---->>> result", afterResult);
    })
    .catch((error) =>{
        console.log("show error ->>>", error); 
    })
```
    
### Relevant log output
When we start error shows: 
```
   DFU State: DEVICE_DISCONNECTING
   DFU State: DFU_FAILED
   show error ->>> [Error: DFU CHARACTERISTICS NOT FOUND]
```

**Comment by philips77** [comment]
This library supports Legacy and Secure DFU from Nordic nRF5 SDK.

Make sure your device supports it and the service UUID and characteristic UUIDs are the same. If the protocol is the same, but the UUIDs have been modified, you can use `UuidHelper` to assign the right ones.

If your device does not support any of these, for example uses nRF Connect SDK's McuMgr, use a different library, which is design for that DFU protocol.

**Comment by faisalm70033** [comment]
I am detect my device have SMP service and Nordic DFU not support SMP service for DFU update in react native .
how can we do DFU update with SMP service  ? In react native.

**Comment by philips77** [comment]
Hi,
I've never tried, but you may try this library: https://github.com/PlayerData/react-native-mcu-manager

**Comment by faisalm70033** [comment]
Thanks,
Butt this Library use in expo only but my project create in cli ?

**Comment by philips77** [comment]
Sorry, but I have no idea what it means. You may search for another wrapper or write your own. We only provide native implementations and a Flutter wrapper, which we needed for one project.

**Comment by faisalm70033** [comment]
I am create a project in react native with BLE Manager scan and connect device work perfectly write and read data perfectly but when i am try to update DFU with the help of Nordic DFU show error characteristic not found when we search on it my device have SMP service which is not work with Nordic DFU .
Then you share another library (library: https://github.com/PlayerData/react-native-mcu-manager)
but this library work with expo because two platform in react native one is expo and other is CLI i am work with CLI that is why i am not work with your shared library any other idea you have please share with me ?

**Comment by jameelwahab** [comment]
Error: DFU CHARACTERISTICS NOT FOUND

Hi @faisalm70033,

 I am facing the same issue in React Native CLI, any solution ?

**Comment by faisalm70033** [comment]
Try to create bridge in react native for Android and iOS i am  use this library "no.nordicsemi.android:mcumgr-ble:1.8.1" for android and 
for iOS "iOSMcuManagerLibrary"

**Comment by philips77** [comment]
Also, try connecting to the device using nRF Connect app and verify that the Secure DFU or Legacy DFU service is there with all the required characteristics. 

> [!Note]
> If your fw is based on nRF Connect SDK or Zephyr, you should be using *nRF Connect Device Manager* library instead. This one is only for DFU based on nRF5 SDK.
