### ISSUE TITLE
DFU版本问题

### ISSUE THREAD

**Issue by hjjice** [NordicSemiconductor/Android-DFU-Library#460]
### Version

None

### Ask the question

你好，我有个问题，DFU有打算做鸿蒙SDK吗，如果会做，大概什么时候做呢，你也知道鸿蒙next不再支持Android，我们需要迫切需要鸿蒙DFU  SDK   ；扫描和连接的反而可以用原声，还没那么急

**Comment by philips77** [comment]
由于资源不足，我们不打算在可预见的未来支持鸿蒙 SDK。请随意克隆项目并进行必要的更改。
