### ISSUE TITLE
Is there any plane to port to React-Native lib in someday?

### ISSUE THREAD

**Issue by dubiao** [NordicSemiconductor/Android-DFU-Library#52]
I am about to create our next project base on React-Native tech. It's easy to get normal BLE functions to work but the DFU is a little difficult for me. I try port it by myself but get many more insolubility problems.

> I posted this issue on IOS-Pods-DFU-Library repository also. see [here](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/issues/99).

**Comment by philips77** [comment]
As Mostafa wrote in the other issue on iOS-Pods-DFU-Library project we do not plan to support.
