### ISSUE TITLE
EXTRA_RESTORE_BOND

### ISSUE THREAD

**Issue by troyjperales** [NordicSemiconductor/Android-DFU-Library#56]
Is this purposefully not exposed via DfuServiceInitiator? There doesn't appear to be any way to set it to true.

**Comment by philips77** [comment]
Hi, thanks for reporting it. I'll check it and add it in the next version. Until now you can just copy paste the initiator to your project and add what you need.

**Comment by philips77** [comment]
This will be released in the next version.
