### ISSUE TITLE
Connection state change error: 8 newState: 0, error: 133 newState: 0

### ISSUE THREAD

**Issue by KwonGiho** [NordicSemiconductor/Android-DFU-Library#63]
Hi I'm junior developer both Android and Bluetooth.

I have a problem with error code 133 while updating new firmware using DFU
There is serve message "DFU DEVICE DISCONNECTED" after show error message

In my case, I use local server for debug.
The server is a type of storage server to download new firmware to upgrade new firmware.

I use new version 13 of DFU.

I already read all issues about this error code 133 in this repository.

The code below is my Android Monitor logcat.

07-21 17:12:37.793 18936-18948/- **## E/DfuBaseService: Connection state change error: 8 newState: 0**
07-21 17:12:37.795 18936-19430/- D/BluetoothGatt: refresh() - device: DE:98:3E:06:59:A6
07-21 17:12:37.801 18936-19430/- D/BluetoothGatt: close()
07-21 17:12:37.805 18936-19430/- D/BluetoothGatt: unregisterApp() - mClientIf=6
07-21 17:12:37.813 18936-19430/- D/BluetoothAdapter: STATE_ON
07-21 17:12:37.816 18936-19430/- D/BluetoothAdapter: STATE_ON
07-21 17:12:37.817 18936-19430/- D/BluetoothLeScanner: Start Scan
07-21 17:12:37.818 18936-19430/- D/BluetoothAdapter: STATE_ON
07-21 17:12:37.819 18936-19430/- D/BluetoothAdapter: STATE_ON
07-21 17:12:37.822 18936-19430/- D/BluetoothAdapter: STATE_ON
07-21 17:12:37.824 18936-19430/- D/BluetoothAdapter: STATE_ON
07-21 17:12:37.946 18936-19147/- D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=6 mClientIf=0
07-21 17:12:38.010 18936-18949/- D/ScanRecord: parseFromBytes
07-21 17:12:38.010 18936-18949/- D/ScanRecord: first manudata for manu ID
07-21 17:12:38.016 18936-19148/- D/ScanRecord: parseFromBytes
07-21 17:12:38.016 18936-19148/- D/ScanRecord: first manudata for manu ID
07-21 17:12:38.023 18936-18948/- D/ScanRecord: parseFromBytes
07-21 17:12:38.037 18936-19148/- D/ScanRecord: parseFromBytes
07-21 17:12:38.042 18936-18948/- D/ScanRecord: parseFromBytes
07-21 17:12:38.049 18936-19430/- D/BluetoothAdapter: STATE_ON
07-21 17:12:38.050 18936-19430/- D/BluetoothAdapter: STATE_ON
07-21 17:12:38.050 18936-19430/- D/BluetoothLeScanner: Stop Scan
07-21 17:12:40.110 18936-19430/- D/BluetoothGatt: connect() - device: DE:98:3E:06:59:A6, auto: false
07-21 17:12:40.110 18936-19430/- D/BluetoothAdapter: isSecureModeEnabled
07-21 17:12:40.111 18936-19430/- D/BluetoothGatt: registerApp()
07-21 17:12:40.111 18936-19430/- D/BluetoothGatt: registerApp() - UUID=63755e3f-8a14-4612-a639-d7e29f2ca3e4
07-21 17:12:40.220 18936-18948/- D/BluetoothGatt: onClientRegistered() - status=0 clientIf=6
07-21 17:12:40.670 18936-18948/- D/BluetoothGatt: onClientConnectionState() - status=133 clientIf=6 device=DE:98:3E:06:59:A6
07-21 17:12:40.675 18936-18948/- **## E/DfuBaseService: Connection state change error: 133 newState: 0
07-21 17:12:40.676 18936-19430/- E/DfuBaseService: Device got disconnected before service discovery finished**

And Its my code that using SDK 13 DFU
```
public static void update(final Context context,
                              final String addr,
                              final UpdateCallback callback) {

        if (sCached == null) {
            return;
        }

        DownloadFileService service = new Retrofit.Builder()
                .baseUrl(BASE_DOWNLOAD_URL).build().create(DownloadFileService.class);

        Call<ResponseBody> q = service.download(sCached.mResourceUri);
        q.enqueue(new Callback<ResponseBody>() {
            @Override
            public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {

                try {
                    final File tempFile = File.createTempFile(String.valueOf(System.currentTimeMillis()), null);

                    FileOutputStream writer = new FileOutputStream(tempFile);
                    writer.write(response.body().bytes());
                    writer.close();

                    new DfuServiceInitiator(addr)
                            .setKeepBond(false)
                            .setDisableNotification(true)
                            .setZip(Uri.fromFile(tempFile), tempFile.getPath())
                            .start(context, DfuService.class);

                } catch (IOException e) {
                    e.printStackTrace();
                    if (callback != null) {
                        callback.onFailure(e);
                    }
                }
            }

            @Override
            public void onFailure(Call<ResponseBody> call, Throwable t) {
                if (callback != null) {
                    callback.onFailure(t);
                }
            }
            /**
             * Logger for Debug only.
             * @param logStr log message.
             */
            private void log(String logStr) {
                Log.e(TAG,logStr);
            }
        });
    }
```

I'll wait for your reply! thank you.

The error code 133 is disable after set the time to short time such as 1000ms . but idk why disabled this error.

**Comment by philips77** [comment]
Hi, the error 8 is timeout, looks like your device wasn't accessible at the time. Error 133 is caused by internal problems of Bluetooth LE stack on Android. Usually happens when resources weren't released, the device doesn't respond with something expected, or has sent something unexpected. Usually restarting Bluetooth or adding some delays helps.
