### ISSUE TITLE
Test the library with a Silicon Labs MCU

### ISSUE THREAD

**Issue by leof23** [NordicSemiconductor/Android-DFU-Library#73]
Hi have a question, can I use this library for an OTA firmware update in any brand of MCU, I'm trying to implement this library to make an OTA update to my Silicon Labs Blue Gecko(BGM121) MCU but always obtain this result.

`10-04 16:38:56.572 2857-5032/com.cartier.croxel.cartier I/DfuBaseService: Connecting to the device...
10-04 16:38:58.902 2857-2857/com.cartier.croxel.cartier I/DfuBaseService: Action received: android.bluetooth.device.action.ACL_CONNECTED
10-04 16:38:58.902 2857-3014/com.cartier.croxel.cartier I/DfuBaseService: Connected to GATT server
10-04 16:38:58.912 2857-3014/com.cartier.croxel.cartier I/DfuBaseService: Attempting to start service discovery... succeed
10-04 16:38:59.622 2857-2872/com.cartier.croxel.cartier I/DfuBaseService: Services discovered
10-04 16:38:59.622 2857-5032/com.cartier.croxel.cartier W/DfuBaseService: DFU Service not found.
10-04 16:38:59.642 2857-5032/com.cartier.croxel.cartier I/DfuBaseService: Disconnecting from the device...
10-04 16:38:59.642 2857-3014/com.cartier.croxel.cartier I/DfuBaseService: Disconnected from GATT server
10-04 16:38:59.652 2857-5032/com.cartier.croxel.cartier I/DfuBaseService: Refreshing result: true
10-04 16:38:59.652 2857-5032/com.cartier.croxel.cartier I/DfuBaseService: Cleaning up...`

Thanks for the help

**Comment by philips77** [comment]
This library is compatible only with Nordic's Device Firmware Update (DFU) bootloader. Will not work with other manufacturer's services.
