### ISSUE TITLE
Android DFU upgrade function package use confusion after error, upgrade function is invalid

### ISSUE THREAD

**Issue by adsfpj** [NordicSemiconductor/Android-DFU-Library#83]
Android DFU upgrade function package use confusion after error, upgrade function is invalid

#dfu
-dontwarn no.nordicsemi.android.**
-keep class no.nordicsemi.android.** { *; }

-keepattributes Signature
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.stream.** { *; }
-keep class com.google.gson.examples.android.model.** { *; }
-keep class com.google.gson.** { *;}
-keep class no.nordicsemi.android.dfu.manifest.** {*;}

-keep class com.null.test.entities.** {
    *;
}![wechatimg1](https://user-images.githubusercontent.com/33408128/32428663-8e12f8e2-c28c-11e7-9769-32e43ba05bc9.jpeg)

**Comment by philips77** [comment]
Hi, it looks like your manifest file is invalid. The name of the bin file specified in the manifest does not match the application bin file in the ZIP, or the bin file is missing. The error comes from here: https://github.com/NordicSemiconductor/Android-DFU-Library/blob/release/dfu/src/main/java/no/nordicsemi/android/dfu/internal/ArchiveInputStream.java#L136

The correct ZIP packet should have 3 or 5 files inside:
![zip](https://user-images.githubusercontent.com/6576580/32433827-937ea29a-c2dc-11e7-9e24-d7f9054cb50f.png)
If your distribution file contains only the application firmware, the `sd_bl.*` should not be there.

Here's an example of a correct manifest file matching those files for legacy DFU:
```json
{
    "manifest": {
        "application": {
            "bin_file": "ble_app_hrm_dfu_s132_v2_0_0_sdk_11_0.bin",
            "dat_file": "ble_app_hrm_dfu_s132_v2_0_0_sdk_11_0.dat",
            "init_packet_data": {
                "application_version": 4294967295,
                "device_revision": 65535,
                "device_type": 65535,
                "firmware_crc16": 37812,
                "softdevice_req": [
                    65534
                ]
            }
        },
        "dfu_version": 0.5,
        "softdevice_bootloader": {
            "bin_file": "sd_bl.bin",
            "bl_size": 13324,
            "dat_file": "sd_bl.dat",
            "init_packet_data": {
                "application_version": 4294967295,
                "device_revision": 65535,
                "device_type": 65535,
                "firmware_crc16": 29480,
                "softdevice_req": [
                    65534
                ]
            },
            "sd_size": 106484
        }
    }
}
```

and for Secure DFU:
```json
{
    "manifest": {
        "application": {
            "bin_file": "ble_app_hrm_dfu_s132_v2_0_0_sdk_14_1.bin",
            "dat_file": "ble_app_hrm_dfu_s132_v2_0_0_sdk_14_1.dat"
        },
        "softdevice_bootloader": {
            "bin_file": "sd_bl.bin",
            "dat_file": "sd_bl.dat",
            "info_read_only_metadata": {
                "bl_size": 13324,
                "sd_size": 106484
            }
        }
    }
}
```
Of course you may name the app and sd/bl files however you want, just make sure the manifest has the same names.

**Comment by adsfpj** [comment]
It seems not the problem, then why I confused when the package is all right, the use of confusion packaging will have this problem

**Comment by philips77** [comment]
Does it work without proguard?

**Comment by adsfpj** [comment]
without proguard it work

**Comment by philips77** [comment]
Hi, did you manage to solve this issue?
How about adding:
```gradle
-keep class no.nordicsemi.android.dfu.** { *; }
```
to the *proguard-rules.pro*?

**Comment by adsfpj** [comment]
No.
￼￼
![1511251851356](https://user-images.githubusercontent.com/33408128/33061293-91cbb158-ced6-11e7-92c4-7c1b07ffe859.jpg)
￼

**Comment by philips77** [comment]
Looks like the `@SerializeName` annotation has been removed by proguard.
How about adding:
```gradle
-keep com.google.gson.annotations.SerializeName
-keepclassmembers class no.nordicsemi.android.dfu.internal.manifest.** { *; }
```
or
```gradle
-keepattributes *Annotation*
```
I'm reading this: https://stackoverflow.com/questions/15476315/how-keep-my-class-from-obfuscate-by-proguard. Also, here: http://movingbitseasy.blogspot.no/2015/01/proguard-android-obfuscation.html they write that:

> One possibility is to use `@SerializedName` annotation do set a static name for an attribute, which is not affected from obfuscation.

For some reason your proguard removes it.

**Comment by philips77** [comment]
Hi, did you manage to fix the issue? It hangs here almost an year.

**Comment by adsfpj** [comment]
It was solved a year ago.


-dontwarn no.nordicsemi.android.**
-keep class no.nordicsemi.android.** { *; }
-keep class com.google.gson.** { *;}
-keepclassmembers class no.nordicsemi.android.dfu.internal.manifest.** { *; }
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}





------------------ 原始邮件 ------------------
发件人: "Aleksander Nowakowski"<notifications@github.com>;
发送时间: 2018年10月24日(星期三) 晚上8:08
收件人: "NordicSemiconductor/Android-DFU-Library"<Android-DFU-Library@noreply.github.com>;
抄送: "Sly"<1426172469@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NordicSemiconductor/Android-DFU-Library] Android DFU upgradefunction package use confusion after error, upgrade function is invalid (#83)




Hi, did you manage to fix the issue? It hangs here almost an year.

**Comment by adsfpj** [comment]
It has been solved.

-dontwarn no.nordicsemi.android.**
-keep class no.nordicsemi.android.** { *; }
-keep class com.google.gson.** { *;}
-keepclassmembers class no.nordicsemi.android.dfu.internal.manifest.** { *; }
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

**Comment by philips77** [comment]
Great, thanks for letting us know!
