### ISSUE TITLE
Android support library version incompatibility

### ISSUE THREAD

**Issue by tekinalper** [NordicSemiconductor/Android-DFU-Library#85]
Hi, 
I don't use push notification during DFU process. So if I use the library as dependency, I'm having support library version incompatibility issue as I need to use lower version on the app side.
 
Is there any way to bypass NotificationCompat usage with excluding support lib? Otherwise, I will add the library manually.

**Comment by philips77** [comment]
Check this file:
https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/master/wear/build.gradle
at very bottom. Perhaps it could work for you, just set there your support version (27.0.0?)
