### ISSUE TITLE
Unable to Run in android Studio

### ISSUE THREAD

**Issue by VinayTShetty** [NordicSemiconductor/Android-DFU-Library#91]
After extracting the ZIP file i am unable to See the RUN button in android Studio.
![screenshot1](https://user-images.githubusercontent.com/33421892/34667046-51604160-f48d-11e7-8791-86aeaff81f75.PNG)
![screenshot2](https://user-images.githubusercontent.com/33421892/34667047-518dc3d8-f48d-11e7-8972-9e246d6b5384.PNG)
![screenshot3](https://user-images.githubusercontent.com/33421892/34667048-51b7577a-f48d-11e7-88a6-86401d6bee6c.PNG)

**Comment by philips77** [comment]
Of course. This is a library, not an app.

**Comment by VinayTShetty** [comment]
@philips77 
Can u please guide me on how to implement this library to the application.

**Comment by philips77** [comment]
nRF Toolbox is using it. See the app/build.gradle file there, it imports the dfu library and then use it in dfu package. Please, read the documentation on DFU lib GitHub page on how to use it.
