### ISSUE TITLE
startForeground fail after update to Android 8.1

### ISSUE THREAD

**Issue by kinber95** [NordicSemiconductor/Android-DFU-Library#96]
My App crash after I update my Nexus 5x to Android 8.1, the reasons is that you need for a Foreground-Service a own NotificationChannel. 

Can I do it on my own, or do you have to update the lib ? 

Cheers

**Comment by philips77** [comment]
You may create your own, but it needs to have the id = [NOTIFICATION_CHANNEL_DFU](https://github.com/NordicSemiconductor/Android-DFU-Library/blob/release/dfu/src/main/java/no/nordicsemi/android/dfu/DfuBaseService.java#L99). You may use this method:
https://github.com/NordicSemiconductor/Android-DFU-Library/blob/release/dfu/src/main/java/no/nordicsemi/android/dfu/DfuServiceInitiator.java#L588
but also may create the channel on your own.

**Comment by kinber95** [comment]
Thanks for the fast answer.

Do I have to create the channel in my NotificationActivity?

**Comment by philips77** [comment]
We usually do it in the Application class in onCreate, so it's done once the app starts. But I have no really clue where it should be done. Doc says it just needs to be done :)

**Comment by kinber95** [comment]
Okay I read the docs again and found at the bottom the method : `DfuServiceInitiator.createDfuNotificationChannel(context);
`

I add it to my firmware update code, know is all good :)

Thanks for the fast help 👍

**Comment by philips77** [comment]
Sure:)
