### ISSUE TITLE
Crash on DfuBaseService class (line #1578)

### ISSUE THREAD

**Issue by datainvent** [NordicSemiconductor/Android-DFU-Library#99]
I updated the sdk from 1.4.2 to 1.6.1 and now whenever i start dfu process my app crashes with the error "No Method found for NotificationCompact.Build in base apk" 
What could be the cause?

**Comment by philips77** [comment]
Looks like a proguard issue.

**Comment by datainvent** [comment]
I am using gradle @philips77

**Comment by philips77** [comment]
Did you enable proguard in your gradle file?

**Comment by datainvent** [comment]
No. Does it have anything to do with the compiled sdk version? I am using 27 btw. @philips77

**Comment by philips77** [comment]
Did you also switch support lib to 27.0.2 or 27.1.0 in dependencies?

**Comment by philips77** [comment]
https://stackoverflow.com/questions/41242832/fatal-exception-java-lang-nosuchmethoderror-no-interface-method-build-no-int

**Comment by philips77** [comment]
Hi, did you manage to solve the issue?
